"""Country profile definitions used by debate agents and API responses."""

COUNTRY_PROFILES = {
    "USA": {
        "name": "USA",
        "stance": "Innovation-focused, pragmatic",
        "tone": "Business-oriented",
        "goals": ["Protect tech innovation", "Maintain competitive advantage"],
        "aggression_level": 0.6,
        "cooperation_level": 0.5,
        "flag": "🇺🇸",
        "color": "#3b82f6",
    },
    "European Union": {
        "name": "European Union",
        "stance": "Regulation-first, precautionary",
        "tone": "Formal, legalistic",
        "goals": ["Establish strict regulations", "Protect citizen rights"],
        "aggression_level": 0.4,
        "cooperation_level": 0.7,
        "flag": "🇪🇺",
        "color": "#8b5cf6",
    },
    "China": {
        "name": "China",
        "stance": "State-controlled development",
        "tone": "Strategic, collaborative",
        "goals": ["Advance state capabilities", "Balance innovation and control"],
        "aggression_level": 0.5,
        "cooperation_level": 0.6,
        "flag": "🇨🇳",
        "color": "#ec4899",
    },
    "India": {
        "name": "India",
        "stance": "Development-conscious",
        "tone": "Inclusive, opportunity-focused",
        "goals": ["Ensure inclusive development", "Prevent digital divide"],
        "aggression_level": 0.3,
        "cooperation_level": 0.8,
        "flag": "🇮🇳",
        "color": "#f59e0b",
    },
    "United Kingdom": {
        "name": "United Kingdom",
        "stance": "Balanced, pragmatic",
        "tone": "Thoughtful, analytical",
        "goals": ["Balance innovation and safety", "Support responsible research"],
        "aggression_level": 0.4,
        "cooperation_level": 0.7,
        "flag": "🇬🇧",
        "color": "#10b981",
    },
}
